/*
 * Multiverse Telemetry API
 * A simplified version of the Controller-Agent pub-sub API for telemetry.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.pubsub.controller;

// Controller Main

public class Main {

	public static void main(String[] args) {
		// start Controller
	}
}
